# Python Review / Révision de Python

Reviewing some basic concepts in Python

* **`help` function**    
    When needed, use `help` to get the information about a function and the parameters it takes (e.g. `help(range)`)
    
<hr />
    
Revoyons quelques concepts de base avec Python.

* **fonction `help`**
  
  Au besoin, afin d'obtenir de l'information sur l'usage et les paramètres d'une fonction, utilisez help (ex: help(range)).

In [2]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |
 |  Methods defined here:
 |
 |  __bool__(self, /)
 |      self != 0
 |
 |  __contains__(self, key, /)
 |      Return key in self.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  __reduce__(...)
 |      helper for pickle
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(...)
 |      Return a reverse iterator.
 |
 |  count(...)
 |      rangeobject.count(value) -> integer -- return number of occurrences of value
 |
 |  index(...)
 |      rangeobject.index(value, [start, [stop]]) -> integer -- return index of value.
 |      Raise ValueError if the value is not present.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  start
 |
 |  step
 |
 |  stop

* **Data structure `list`**.

A list is a sequence of items (numbers, or strings, etc.) For e.g., `a = [1, 2, 3, 4]`

***Ex 1: Create a list with the numbers 0-9 (including 9) in increasing order using `range`. Then create one in decreasing order.***

<hr />


* **Structure de données `list`**.

Une liste est une séquence d'items (des entiers, des chaînes de caractères, etc.). Par exemple, `a = [1, 2, 3, 4]`

***Ex 1: Créez une liste en ordre croissant des nombres allant de 0 à 9 (incluant 9) en utilisant la fonction `range`. Créez une liste décroissante des mêmes nombres.***

In [0]:
# insert code here/ insérer votre code ici

* **Slicing a list**

You can "choose" some elements of a list using square brackets with the index of the elements you want For example, `l[0]` returns the 1st element of the list `l`; `l[:4]` returns the first 4 elements.

In general, "slicing" is done using `l[a:b:c]`, where `a` is the first element index you want to slice, `b` is the last index, `c` is the spacing between indices you slice.

***Ex 2: Create a list of the numbers 0-9. Slice it to return only even numbers.***  
***Ex 3: Create a list of the numbers 0-9. Slice it to return only odd numbers.***

<hr />

* **Découper une liste**.

Il est possible de sélectionner des éléments d'une liste en utilisant l'index de ces éléments. Par exemple, `l[0]` retourne le premier élément de la liste `l` et `l[:4]` retourne les 4 premiers éléments.

De manière générale, le <em>découpage</em> est utilisé comme suit `l[a:b:c]` où `a` représente l'index du premier élément à découper, `b` est l'index du dernier élément et `c` est le saut avec lequel ceux-ci sont découpés. 

***Ex 2: Créez une liste de nombres allant de 0 à 9. Découper cette liste pour y inclure seulement les nombres pairs.***  
***Ex 3: Créez une liste de nombres allant de 0 à 9. Découper cette liste pour y inclure seulement les nombres impairs.***

In [0]:
# insert code here/ insérer votre code ici

* **`for` loop**

A `for` loop is a "loop" that runs until some condition is exhausted. For example, if `a` is a list of numbers,
```
for i in range(len(a)):
    print(a[i])
```
prints each element in a.

Note that the 1st line defines the loop condition, and every **indented** line after that defines what to do **for** each run of the loop (in this case, to print an element of `a`).

***Ex 4: Create a list of numbers 0-9. Find its sum using a `for` loop, and print it.***


<hr />


* **Boucle `for`**

Une boucle `for` est une <em>boucle</em> qui exécute jusqu'à ce qu'une condition soit remplie. Par exemple, si `a` est une liste de nombres:
```
for i in range(len(a)):
    print(a[i])
```

imprime chaque élément de `a`.

Notez que la première ligne définit la condition à remplir et chaque ligne ensuite contenant une indentation définit ce qu'il faut exécuter à chaque pas de la boucle (ici, il s'agit d'imprimer un élément de `a)`.


***Ex 4: Créez une liste de nombres allant de 0 à 9. Trouvez la somme de ces éléments en utilisant une boucle `for` et ensuite imprimez la.***

In [0]:
# insert code here/ insérer votre code ici

* **List of lists**

A 2-dimensional matrix can be represented by a list of lists. For example,
`m = [[1, 2], [3, 4], [5, 6], [7, 8]]` represents a 4x2 matrix.

Each element of `m` can be accessed using square brackets. For example, `m[2]` returns the 3rd row of `m`; `m[2][0]` returns the 1st element in the 3rd row.

***Ex 5: Create the above m. Calculate the sum of all its elements using a/multiple `for` loops.***


<hr />


* **Une liste de listes**

Une matrice à 2 dimensions peut être représentée par une liste de listes. Par exemple, `m = [[1, 2], [3, 4], [5, 6], [7, 8]]` représente une matrice de dimension 4x2.

Pour chaque élément de `m`; `m[2][0]` retourne le premier élément de la troisième ligne.

***Ex 5: Créez ladite liste `m`. Calculez la somme de tous ses éléments en utilisant des boucles `for` imbriquées.***

In [0]:
# insert code here/ insérer votre code ici

* **Defining functions with `def`**.      
    this is how you define a function to add one to a number

        def plus_one(s):
            return s + 1

    note the indentation! whitespace matters in Python!
    
<hr />
    
* **Définir des fonctions avec `def`**.      
    Voici comment on pourrait définir une fonction "plus un":

        def plus_un(s):
            return s + 1

    Notez l'importance de l'indentation!

# Numpy

*Note*: if you're familiar with MATLAB, [this page](http://www.scipy.org/NumPy_for_Matlab_Users) will allow you to see the corresponding numpy terms to functions you already know.

*Note:* Si vous êtes familier avec MATLAB, cette [page web](http://www.scipy.org/NumPy_for_Matlab_Users) vous permettra de consulter les principales correspondances matlab/numpy en terme de syntaxe.

## Basics / Bases

Numpy is a package in Python. It needs to be imported.

Numpy est une librairie Python. Il faut ainsi l'importer.

In [0]:
import numpy as np

All documentation for every function in numpy can be found in its [docs](https://docs.scipy.org/doc/numpy/reference/). It is a good practice to keep referring to the docs to understand any function you use, and its proper syntax.

***Ex 6: using `np.arange`, create an array of the numbers 0-9***

<hr />

Toute la documentation pour chacune des fonctions numpy se retrouve ici [docs](https://docs.scipy.org/doc/numpy/reference/). Une bonne habitude est de se réferer à la documentation afin de bien comprendre une fonction utilisée et sa syntaxe.

***Ex 6: utilisez `np.arange` afin de créer un tableau des nombres 0 à 9***

In [0]:
# insert code here/ insérer votre code ici


***Ex 7: print the `type` of the array***

***Ex 8: print the `type` of the first element in the array***

***Ex 9: print the `shape` of the array***

<hr />

***Ex 7: imprimez le `type` de votre tableau***

***Ex 8: imprimez le `type` du premier élément de votre tableau***

***Ex 9: imprimez la dimension (`shape`) du tableau***

In [0]:
# insert code here/ insérer votre code ici

We see that the array is of the type `numpy.ndarray`: "Numpy n-dimensional array", while each element in it is an integer.

***Ex 10: Print the numbers at the 3rd to the 6th index in the array using slicing `[:]`***

<hr />

On remarque que le tableau est de type `numpy.ndarray`: "Numpy n-dimensional array" et que chaque élément est un entier.

***Ex 10: Accédez aux éléments 3 à 6 à l'aide de l'opérateur «`[:]`».***

In [0]:
# insert code here/ insérer votre code ici

***Ex 11: Create a list of the numbers 0-9, convert it into a numpy array using `np.array`***

<hr />

***Ex 11: Créez une liste des nombres 0 à 9 et convertissez la en tableau en utilisant `np.array`***

In [0]:
# insert code here/ insérer votre code ici

***Ex 12: Create a list of lists of size 4x2 (like the one we did earlier). Convert it into a numpy array, check its shape.***

<hr />

***Ex 12: Créez une liste de listes de dimension 4x2 (comme celle que nous avons définie précédemment). Convertissez la en tableau et vérifiez sa dimension.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 13: Find the sum of all the elements in this numpy array using `np.sum`. Then, find the sum along the 1st axis.*** Think about what shape the sum must be, and then verify.

<hr />

***Ex 13: Trouvez la somme de tous les éléments du tableau en utilisant `np.sum`. Ensuite, trouvez la somme selon la première dimension*** Pensez à la dimension que cette somme devrait avoir et vérifiez la.

In [0]:
# insert code here/ insérer votre code ici

## Statistics/ Statistiques

Now we're going to generate data points and verify statistics

***Ex 14: Create a 2D array `o` of shape (100, 2) filled with the number 1 using `np.ones`***

<hr />

Nous allons maintenant générer des points et vérifiez certaines de leurs statistiques.

***Ex 14: Créez un tableau 2D `o` de dimension (100, 2) composé uniquement de 1 en utilisant `np.ones`***

In [0]:
# insert code here/ insérer votre code ici

***Ex 15: Create a 2D array `n` of shape (100, 2) filled with samples from a normal distribution with mean 2.5 and standard deviation 1.2 using `np.random.normal`.***

<hr />

***Ex 15: Créez une tableau 2D `n` de dimension (100,2) composés de points provenant d'une distribution de loi normale avec une moyenne de 2.5 et un écart-type de 1.2. Utilisez la fonction `np.random.normal`.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 16: Using slicing, assign the first column of `o` as values from the 2nd column of `n`***

<hr />

***Ex 16: En utilisant le découpage, remplacez les valeurs de la première colonne de `o` avec les valeurs de la deuxième colonne de `n`.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 17: Calculate the mean and std of ech column of `o` using `np.mean` and `np.std`.*** Verify that they are (almost) correct.

<hr />

***Ex 17: Calculez la moyenne et l'écart-type de chaque colonne de `o` en utilisant `np.mean` et `np.std`.*** Vérifiez si ces valeurs sont approximativement exactes.

In [0]:
# insert code here/ insérer votre code ici

# Fun with the IRIS dataset / Exploration du jeu de données IRIS

We're now going to work with some real data! We'll use the [IRIS](http://en.wikipedia.org/wiki/Iris_flower_data_set) dataset which you can download [here](http://www.iro.umontreal.ca/%7Edift3395/files/iris.txt).
<hr />

Nous allons maintenant travailler avec de vraies données! Nous allons utiliser le jeu de données [IRIS](http://en.wikipedia.org/wiki/Iris_flower_data_set) dont vous pouvez télécharger [ici](http://www.iro.umontreal.ca/%7Edift3395/files/iris.txt).

In [0]:
import sys
IN_COLAB = 'google.colab' in sys.modules
if IN_COLAB:
  iris = np.loadtxt('http://www.iro.umontreal.ca/~dift3395/files/iris.txt')
else:
  iris = np.loadtxt('iris.txt')

The IRIS dataset consists of 150 data points. Each data point is a description of a flower using 4 features - petal length, petal width, sepal length, sepal width. The dataset also contains the species of the flower. Thus, the samples form the 1st axis of this np array, and (the features + the species) form the 2nd axis of the array.

Let's play around with the *array* of iris data

* print the shape of the array
* print all the elements of the array


<hr />

Le dataset IRIS consiste en 150 points de données. Chaque exemple (point) représente une description d'une fleur à l'aide de 4 variables, soient la longueur des pétales, la largeur des pétales, la longueur des sépales et la largeur des sépales. Ce jeu de données contient également l'espèce de la fleur. La première dimension représente ainsi les différents exemples et la deuxième dimension représente les variables et l'espèce de ces exemples.


Explorons le tableau de donnees

* imprimez la dimension du tableau
* imprimez les éléments du tableau

In [0]:
print(iris.shape)
print(iris)

Accessing an element in a `np.array` is similar but not the same as a python `list`

***Ex 18: Get the first element (i.e. index 0,0) of `iris` using `[][]`.***

***Ex 19: Get the first element of the `np.array` using just `[,]` syntax.***

<hr />


Acccéder un élément d'un tableau est similaire, mais pas tout à fait pareil à une liste python

***Ex 18: Obtenez le premier élément (i.e. index 0,0) du dataset iris en utilisant `[][]`.***

***Ex 19: Obtenez le premier élément du tableau en utilisant la syntaxe `[,]`.***

In [0]:
# insert code here/ insérer votre code ici

The advantage of `numpy` slicing is that you can access multiple dimensions (`axis`) at the same time

***Ex 20: Slice the 4 features of the first 10 samples of the IRIS dataset.***

<hr />

L'avantage du découpage `numpy` est qu'il est possible d'accéder plusieurs dimensions (`axis`) simultanément


***Ex 20: Découpez les 4 variables des 10 premiers exemples du dataset IRIS.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 21: Using negative index, print the last column of `iris`.***

<hr />

***Ex 21: Utilisez une indexation négative afin d'imprimer la dernière colonne de `iris`.***

In [0]:
# insert code here/ insérer votre code ici

## Some useful `numpy` functions / Quelques fonctions `numpy` utiles

**min**, **max** : minimum and maximum elements of an array (can also be done across an `axis`)

<hr />

**min**, **max** : éléments minimum and maximum d'un tableau (peut également se faire selon une dimension `axis`)

<br/>

**argmax**, **argmin** : the indices of the minimum and maximum elements of an array (can also be done across an `axis`)

<hr />

**argmax**, **argmin** : les indices des minimums ou maximums d'un tableau (peut également se faire selon une dimension `axis`)

<br/>

**abs** : absolute value

<hr />

**abs** : valeur absolue

<br/>

<b>pow or **</b> : exponentiation

<hr />

<b>pow or **</b> : exponentiation

<br/>

**np.random.shuffle** : randomly shuffle the elements in the array

<hr />

**np.random.shuffle** : mélanger de manière aléatoire les éléments d'un tableau

<br/>

`numpy` has many more useful mathematical functions such as:

`numpy` possède plusieurs autres fonction mathématiques utiles telles que:

* numpy.mean
* numpy.std
* numpy.cov
* numpy.dot
* numpy.invert
* numpy.unique
* numpy.vsplit
* numpy.vstack
* numpy.hsplit
* numpy.hstack

You can find all of them on the [documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

***Ex Play: Play around with these!***

Elle se retrouvent toutes dans la [documentation](http://docs.scipy.org/doc/numpy/reference/index.html)

***Ex Play: Explorez avec ces fonctions!***

# Plotting the flowers with Matplotlib

`matplotlib` is a great library for creating charts and graphs. Here are some practical function to visualize a dataset like `iris`.

<hr />

`matplotlib` est une excellente librairie pour créer des diagrammes et des graphiques. Voici quelques fonctions pratiques qui vous aidrons à visualiser le dataset `iris`.

In [0]:
import matplotlib.pyplot as plt

***Ex 22: Plot the histogram of the 2nd feature of every sample in the IRIS dataset using `plt.hist`. Make sure to include both x and y labels and a title.***

<hr />

***Ex 22: Tracez l'histogramme de la deuxième variable de chaque exemple du dataset IRIS en utilisant `plt.hist`. Assurez-vous d'inclure un titre ainsi que les étiquettes d'axes.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 23: Plot a scatterplot, with the 3rd feature as the x-axis and the 4th feature as the y-axis using `plt.scatter`. Make sure to include both x and y labels and a title.***

<hr />

***Ex 23: Tracez un nuage de points avec la troisième variable sur l'axe des x et la quatrième variable sur l'axe des y en utilisant `plt.scatter`. Assurez-vous d'inclure un titre ainsi que les étiquettes d'axes.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 24: Plot the same scatter plot as above, but this time - color the points according to their corresponding "species". Make sure to include both x and y labels and a title.***

<hr/>

***Ex 24: Tracez le même nuage de points mais, colorez les points correspondant aux différentes espèces. Assurez-vous d'inclure un titre ainsi que les étiquettes d'axes.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 25: Plot an errorbar around the average of each of the 4 features across the data samples, using `plt.errorbar`***

<hr/>

***Ex 25: Tracer une barre d'erreur autour des moyennes de chacune des 4 variables en utilisant `plt.errorbar`.***

In [0]:
# insert code here/ insérer votre code ici

***Ex 26: Create a sine wave. Create some gaussian noise. Plot the sine wave, and the sine wave with the noise added to it.***

Try to create this image:

<hr/>

***Ex 26: Créez une courbe  sinusoïdale. Ajoutez-y maintenant du bruit gaussien. Tracez la courbe sinusoïdale sans et avec le bruit ajouté.***

Essayez de recréer cette image:

![reproduce](https://drive.google.com/uc?id=1p_eBFrYEZ9u_Vu2BFisfaQLLoSZbZqjS)

In [0]:
# insert code here/ insérer votre code ici

### This is just the beginning!

You now have some of the basics down but you'll need more practise. Explore new functions and let's go through more tutorials!

---

### Ce n'est que le début!

Vous possédez désormais certaines bases, mais il vous faut plus de pratique. Explorez de nouvelles fonctions et faisons plus de tutoriels!